language: java
jdk:
  - openjdk8
  - openjdk11
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
install:
  - npm install solc
script:
  - gradle check
  - gradle javadoc
after_success:
  - bash <(curl -s https://codecov.io/bash)
